### ISSUE TITLE
certificate verify failed (_ssl.c:897)

### ISSUE THREAD

**Issue by kakaNo1** [DataDog/datadog-api-client-python#991] opened 2022-05-11 11:59 UTC
```
from datadog_api_client.v1 import ApiClient, Configuration
from datadog_api_client.v1.api.tags_api import TagsApi
from datadog_api_client.v1.model.host_tags import HostTags


DD_APP_KEY="xxxx" 
DD_API_KEY="xxxxx" 
DD_SITE="xxxx"

#configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = TagsApi(api_client)
    response = api_instance.list_host_tags()
    print(response)
```
python3.6 1.py
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1.py", line 17, in <module>
    response = api_instance.list_host_tags()
  File "/usr/local/lib/python3.6/site-packages/datadog_api_client/v1/api/tags_api.py", line 346, in list_host_tags
    return self._list_host_tags_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/datadog_api_client/v1/api_client.py", line 788, in call_with_http_info
    collection_formats=params["collection_format"],
  File "/usr/local/lib/python3.6/site-packages/datadog_api_client/v1/api_client.py", line 382, in call_api
    _check_type,
  File "/usr/local/lib/python3.6/site-packages/datadog_api_client/v1/api_client.py", line 133, in _call_api
    _request_timeout=_request_timeout,
  File "/usr/local/lib/python3.6/site-packages/datadog_api_client/v1/rest.py", line 197, in request
    method, url, fields=query_params, preload_content=_preload_content, timeout=timeout, headers=headers
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.datadoghq.com', port=443): Max retries exceeded with url: /api/v1/tags/hosts (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))
```

**Comment by kakaNo1** [comment] 2022-05-12 01:27
I have tried, but I still get an error

```
Traceback (most recent call last):
  File "d:/xxx/xxx/xxxx/xxx.py", line 24, in <module>
    response = api_instance.list_host_tags()
  File "D:\py\lib\site-packages\datadog_api_client\v1\api\tags_api.py", line 351, in list_host_tags
    return self._list_host_tags_endpoint.call_with_http_info(**kwargs)
  File "D:\py\lib\site-packages\datadog_api_client\api_client.py", line 738, in call_with_http_info
    return self.api_client.call_api(
  File "D:\py\lib\site-packages\datadog_api_client\api_client.py", line 362, in call_api
    return self._call_api(
  File "D:\py\lib\site-packages\datadog_api_client\api_client.py", line 122, in _call_api
    response = self.rest_client.request(
  File "D:\py\lib\site-packages\datadog_api_client\rest.py", line 212, in request
    raise ForbiddenException(http_resp=r)
datadog_api_client.exceptions.ForbiddenException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 12 May 2022 01:25:03 GMT', 'Content-Type': 'application/json', 'Content-Length': '25', 'Connection': 'keep-alive', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'x-ratelimit-remaining': '11999', 'x-ratelimit-limit': '12000', 'x-ratelimit-period': '60', 'x-ratelimit-reset': '57', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=15724800;', 'content-security-policy': "frame-ancestors 'self'; report-uri https://logs.browser-intake-datadoghq.com/api/v2/logs?dd-api-key=pube4f163c23bbf91c16b8f57f56af9fc58&dd-evp-origin=content-security-policy&ddsource=csp-report&ddtags=site%3Adatadoghq.com", 'x-frame-options': 'SAMEORIGIN'})
HTTP response body: {'errors': ['Forbidden']}
```

**Comment by therve** [comment] 2022-05-12 06:03
The SSL error is gone though, so that means your credentials are not set properly. You need to set them in the configuration if you don't use env variables: https://github.com/DataDog/datadog-api-client-python#documentation-for-authorization

**Comment by therve** [comment] 2022-05-13 19:27
Closing it for now, feel free to reopen if you're still having issues. Thanks!

**Closed by therve** 2022-05-13 19:27 UTC
Labels: kind/bug

**Comment by Ragamanil** [comment] 2025-06-16 09:28
Hi 
Iam also getting the error  as below
Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (ssl.c:897)'),))
