### ISSUE TITLE
ModuleNotFoundError: No module named 'datadog_api_client.v1.model.point'

### ISSUE THREAD

**Issue by glauesppen** [DataDog/datadog-api-client-python#1497] opened 2023-06-01 14:17 UTC
Hi team,

We started to have this error this morning when installing the `datadog_api_client` and trying to import it `from datadog_api_client.v1.model.point import Point`

Looking on the [docs](https://datadoghq.dev/datadog-api-client-python/datadog_api_client.v1.html), I didnt find it. Was it deprecated?

Thanks!

**Comment by chamini2** [comment] 2023-06-01 14:19
This is because of the changes in https://github.com/DataDog/datadog-api-client-python/pull/1431, so I guess it would be a duplicate of #1496.

**Comment by joseph-galindo** [comment] 2023-06-01 14:21
I am also able to confirm this issue. It seems like the new changes from 2.12.0 -> 2.13.0 do include breaking changes.

**Comment by therve** [comment] 2023-06-01 16:42
You're right, it should have been. We'll add a compatibility layer and make a point release.

**Comment by skarimo** [comment] 2023-06-01 20:04
We have merged a fix and released [`v2.13.1`](https://github.com/DataDog/datadog-api-client-python/releases/tag/2.13.1) of the client. I am going to go ahead and close this issue but feel free to re-open if the issue persists with the latest update. Thanks!

**Closed by skarimo** 2023-06-01 20:04 UTC
Labels: kind/bug

**Comment by glauesppen** [comment] 2023-06-02 10:00
Thank you people!
